#!/bin/bash

#PBS -S /bin/bash
#PBS -l pmem=4000m
#PBS -l feature=X5675
#PBS -l nodes=1:ppn=12
#PBS -l walltime=3:00:00
#PBS -m bea
#PBS -M koch.eric.w@gmail.com
#PBS -l epilogue=/home/ekoch/code_repos/simscript/epilogue.sh

source /home/ekoch/.bashrc

cd /home/ekoch/m33/14B-088/

echo "Starting at: `date`"
echo "Making cleaned cube"
casa -c /home/ekoch/code_repos/VLA_Lband/14B-088/imaging/HI/HI_create_cube.py image
echo "Making residual cube"
casa -c /home/ekoch/code_repos/VLA_Lband/14B-088/imaging/HI/HI_create_cube.py residual
echo "Making model cube"
casa -c /home/ekoch/code_repos/VLA_Lband/14B-088/imaging/HI/HI_create_cube.py model
echo "Making mask cube"
casa -c /home/ekoch/code_repos/VLA_Lband/14B-088/imaging/HI/HI_create_cube.py mask
echo "Exited with code $? at: `date`"
