
from astropy.io import fits
import os
from glob import glob

'''
Add WCS info to the output of DISKFIT
'''

data_path = "/media/eric/MyRAID/M33/14B-088/HI/full_imaging/"

diskfit_output = "diskfit_noasymm_nowarp_output/"

fits_files = glob(os.path.join(data_path, diskfit_output) + "*.fits")

mom1 = \
    fits.open(os.path.join(data_path,
                           "M33_14B-088_HI.clean.image.pbcov_gt_0.3.ellip_mask.mom1.fits"))
header = mom1[0].header.copy()
mom1.close()

header["COMMENT"] = "FILE GENERATED BY DISKFIT"
keep_keys = ['INFILE', 'OUTPFILE', 'COMPS', 'SMAF', 'PIXSCALE', 'XCENOUT',
             'YCENOUT', 'PA_OUT', 'EPS_OUT']

for f in fits_files:
    new_header = header.copy()
    hdu = fits.open(f, mode='update')

    for key in keep_keys:
        new_header[key] = hdu[0].header[key]

    hdu[0].header = new_header
    hdu.flush()
    hdu.close()
